spring:
    profiles:
        active: '@spring.profile@'

server:
    port: 8081

logging:
    level:
        org.atmosphere: warn
        org.springframework: ERROR
        io.recheck: DEBUG
    pattern:
        console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: app.log